services:
  # guacd
  guacd:
#    container_name: guacd_compose
    image: guacamole/guacd
    restart: always
    volumes:
    - /portainer/Files/AppData/Config/Guacamole/guacamole/drive:/drive:rw
    - /portainer/Files/AppData/Config/Guacamole/guacamole/record:/record:rw
  # postgres
  postgres:
#    container_name: postgres_guacamole_compose
    environment:
      PGDATA
      POSTGRES_DB
      POSTGRES_PASSWORD
      POSTGRES_USER
    image: postgres:13.4-buster
    restart: always
    volumes:
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - /portainer/Files/AppData/Config/Guacamole/db:/var/lib/postgresql/data:rw

  # guacamole
  guacamole:
#    container_name: guacamole_compose
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME
      POSTGRES_DATABASE
      POSTGRES_HOSTNAME
      POSTGRES_PASSWORD
      POSTGRES_USER
    image: guacamole/guacamole
    links:
    - guacd
    ports:
## enable next line if not using nginx
    - 8083:8080/tcp # Guacamole is on :8080/guacamole, not /.
## enable next line when using nginx
    #- 8080/tcp
    restart: always
