version: "3"

networks:
  private:
    name: private
    driver: overlay
  public:
    name: public
    driver: overlay

services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID
      - PGID
      - TZ
      - URL
      - SUBDOMAINS
      - VALIDATION
      - DNSPLUGIN
      - EMAIL
    volumes:
      - /portainer/Files/AppData/Config/LetsEncrypt:/config
    ports:
      - 443:443
      - 80:80
    networks:
      - private
      - public
  authelia:
    image: docker.io/authelia/authelia:latest
    #container_name: authelia
    #environment:
    volumes:
      - /portainer/Files/AppData/Config/Authelia:/config
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - private
      - public
