version: '3'
services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - /portainer/Files/AppData/Config/Firefly/upload:/var/www/html/storage/upload
    #env_file: ../stack.env
    ports:
      - 8082:8080
    depends_on:
      - db
    container_name: firefly
  db:
    image: mariadb    
    restart: always
    #env_file: ../stack.env
    volumes:
      - /portainer/Files/AppData/Config/Firefly/db:/var/lib/mysql
  fidi:
    image: fireflyiii/data-importer:latest
    restart: always
    #env_file: ../stack.env
    ports:
      - 8081:8080
    depends_on:
      - app
#volumes:
#  firefly_iii_upload:
#  firefly_iii_db:
