version: '3'
services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - /portainer/Files/AppData/Config/Firefly/upload:/var/www/html/storage/upload
    environment:
      - APP_KEY
      - DB_CONNECTION
      - DB_DATABASE
      - DB_HOST
      - DB_PASSWORD
      - DB_PORT
      - DB_USERNAME
      - SITE_OWNER
      - TRUSTED_PROXIES
      - TZ
    #env_file: stack.env
    published: 8082:8080
    depends_on:
      - db

  db:
    image: mariadb:10.5.4    
    restart: always
   # env_file: stack.env
    environment: 
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    volumes:
      - /portainer/Files/AppData/Config/Firefly/db:/var/lib/mysql

  fidi:
    image: fireflyiii/data-importer:latest
    restart: always
#    env_file: stack.env
    environment:
      - FIREFLY_III_ACCESS_TOKEN
      - FIREFLY_III_URL
      - SPECTRE_APP_ID
      - SPECTRE_SECRET
      - TRUSTED_PROXIES
      - VANITY_URL
    published:  8081:8080
    depends_on:
      - app
#volumes:
#  firefly_iii_upload:
#  firefly_iii_db:
