version: '3'
networks:
  t2_internal:
    external: true

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    networks:
      - t2_internal
    volumes:
      - /portainer/Files/AppData/Config/Firefly/upload:/var/www/html/storage/upload
    environment:
      - APP_KEY
      - DB_CONNECTION
      - DB_DATABASE
      - DB_HOST
      - DB_PASSWORD
      - DB_PORT
      - DB_USERNAME
      - SITE_OWNER
      - TRUSTED_PROXIES
      - TZ
    #env_file: stack.env
#    ports:
#      - 8082:8080
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.firefly-rtr.entrypoints=https"
      - "traefik.http.routers.firefly-rtr.rule=HostHeader(`firefly.vxsan.com`)"
      ## Middlewares
      #- 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.vxsan.com%2F'
      #- 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      #- 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      - "traefik.http.routers.firefly-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      #- "traefik.http.routers.guac-rtr.service=guac_guacamole-svc"
      # - "traefik.http.services.guac-svc.loadbalancer.server.port=8080"      

  db:
    image: mariadb:10.5.4    
    restart: always
    networks:
      - t2_internal    
   # env_file: stack.env
    environment: 
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    volumes:
      - /portainer/Files/AppData/Config/Firefly/db:/var/lib/mysql

  fidi:
    image: fireflyiii/data-importer:latest
    restart: always
    networks:
      - t2_internal    
#    env_file: stack.env
    environment:
      - FIREFLY_III_ACCESS_TOKEN
      - FIREFLY_III_URL
      - SPECTRE_APP_ID
      - SPECTRE_SECRET
      - TRUSTED_PROXIES
      - VANITY_URL
#    ports: 
#      - 8081:8080
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      ## TCP Routers
      - "traefik.tcp.routers.fidi-rtr.entrypoints=https"
      - "traefik.tcp.routers.fidi-rtr.rule=HostSNI(`fidi.vxsan.com`)"
      - "traefik.tcp.routers.fidi-rtr.tls=true"
      ## Middlewares
      #- 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.vxsan.com%2F'
      #- 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      #- 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      # - "traefik.http.routers.fidi-rtr.middlewares=chain-fidi@file"
      ## HTTP Services
      #- "traefik.http.routers.guac-rtr.service=guac_guacamole-svc"
      # - "traefik.http.services.guac-svc.loadbalancer.server.port=8080"          
#volumes:
#  firefly_iii_upload:
#  firefly_iii_db:
